# ===============================
# APPLICATION
# ===============================

spring.application.name=ecommerce-api

# ===============================
# DATASOURCE
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=&D@7wu!Gvr9Sw5RUv6#i

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# SERVER
# ===============================

server.port=8080

# ===============================
# JWT
# ===============================

jwt.secret=5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8
# Expiration time for access tokens (in milliseconds)15
jwt.access-expiration=900000
# Expiration time for refresh tokens (in milliseconds)7 days
jwt.refresh-expiration=604800000
