# ===============================
# APPLICATION
# ===============================

spring.application.name=ecommerce-api

# ===============================
# DATASOURCE
# ===============================

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://db:3306/ecommerce_db}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Password2026!}

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# SERVER
# ===============================

server.port=8080

# ===============================
# JWT
# ===============================

jwt.secret=${JWT_SECRET_KEY:5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8}

jwt.access-expiration=${JWT_ACCESS_EXPIRATION:900000}

jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}